<?php

namespace App\Models;

use App\Models\Scopes\AccountScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class RecipeCategory extends Model
{
    protected $fillable = [
        'name',
        'account_id',
    ];

    public static function booted(): void
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new AccountScope());
    }

    public function recipes(): HasMany
    {
        return $this->hasMany(Recipe::class);
    }

    public function account(): BelongsTo
    {
        return $this->belongsTo(Account::class);
    }
}
